services:
  web:
    build: .
    container_name: receipt_fastapi_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # PC側のコード変更をコンテナにリアルタイム同期
      - ./.env:/app/.env
    env_file:
      - .env
    depends_on:
      - mongodb

# メタデータ・ステータス管理用のNoSQL（MongoDB）
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
