from services.receipt_analysis_service import ReceiptAnalysisService
from services.receipt_job_service import ReceiptJobService

analysis_task = ReceiptAnalysisService.analysis_task
_validate_and_result = ReceiptAnalysisService._validate_and_result
_convert_img_to_raw_text = ReceiptAnalysisService._convert_img_to_raw_text
_process_ocr_analysis = ReceiptAnalysisService._process_ocr_analysis
fetch_job_status = ReceiptJobService.fetch_job_status
lock_receipt_job = ReceiptJobService.lock_receipt_job
fix_receipt_job_data = ReceiptJobService.fix_receipt_job_data
